### ISSUE TITLE
[orb_slam3-2] process has died (exit code -11)

### ISSUE THREAD

**Issue by lazuraihan** [thien94/orb_slam_3_ros#33]
I'm currently working for my study project with ORB-SLAM3 ROS
Whenever i run the examples, it always come up with error.
RViz could visualize the raw image, but it did not work for the slam footage and there is no transform between frame /world and /imu

![error ](https://github.com/thien94/orb_slam3_ros/assets/105598568/9de8bfe8-9790-424c-a176-700a505dc39f)

I'm running it on NVIDIA Jetson nano and ROS Melodic 
Please, can anyone help...

**Comment by Mysterium-sch** [comment]
I had a similar issue that was solved by cloning this repository into src and then rebuilding it.

git clone https://github.com/ros-perception/vision_opencv.git -b noetic

**Comment by lazuraihan** [comment]
@Mysterium-sch Thanky you for the respon...

After I did clonning and rebuilding the repo. The issue is still coming up. Is there any other solution?

**Comment by FahrulRPutra** [comment]
@lazuraihan have you already solved it ?

**Comment by doctorcolossus** [comment]
Hey @lazuraihan, how did you resolve this?

**Comment by oxcarxierra** [comment]
`git clone https://github.com/ros-perception/vision_opencv.git -b noetic` Didn't work for me.
Which makes me crazy is that the log file in that message doesn't even exist...
